services:
  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
      ports:
      - "5000:80"

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
      ports:
      - "6000:80"
